import { createLevel0Map } from "./level0.js";
import { createLevel1Map } from "./level1.js";
import { createLevel2Map, level2Hooks } from "./level2.js";
import { createLevel3Map, level3Hooks } from "./level3.js";
import { createLevel4Map, level4Hooks } from "./level4.js";
import { createLevel5Map, level5Hooks } from "./level5.js";
import { createLevel6Map, level6Hooks } from "./level6.js";
import { createLevel7Map, level7Hooks } from "./level7.js";

export const LEVELS = [
  {
    id: "0",
    name: "Level 0",
    classification: 1,
    classificationLabel: "1",
    startFacing: Math.PI * 0.5,
    ceiling: 3.15,
    tile: 3.1,
    fog: { color: 0xa99745, near: 18, far: 58 },
    ambient: 0xe1ca77,
    hum: { base: 66, buzz: 118, volume: 0.075 },
    createMap: createLevel0Map,
    theme: "level0",
    reviveMessage: "You wake under the buzzing yellow lights.",
    lighting: {
      maxPointLights: 28,
      shouldLight: ({ ctx, manila }) => !manila && ctx.rng() < 0.18,
      color: 0xffefac,
      intensity: 0.72,
    },
    hooks: {
      afterBuild: ({ ctx, addManilaLight }) => {
        if (ctx.manilaZones.length > 0) {
          addManilaLight(ctx);
        }
      },
    },
  },
  {
    id: "1",
    name: "Level 1",
    classification: 2,
    classificationLabel: "2",
    startFacing: Math.PI,
    ceiling: 3.55,
    tile: 3.35,
    fog: { color: 0x9ca19b, near: 11, far: 48 },
    ambient: 0xaeb6a8,
    hum: { base: 57, buzz: 126, volume: 0.055 },
    createMap: createLevel1Map,
    theme: "level1",
    entities: ["hound"],
    reviveMessage: "You wake on the garage floor.",
    lighting: {
      shouldLight: ({ r, c }) => r % 3 === 1 && c % 4 === 2,
      color: 0xddeeff,
      intensity: 0.72,
    },
    hooks: {
      afterBuild: ({ ctx, rows, width, depth, cellCenter, charAt, tile, addGarageLines, addTorchPickup, hasInventoryItem }) => {
        if (!hasInventoryItem("torch")) {
          addTorchPickup(ctx, ctx.start.x + tile * 0.7, ctx.start.z + tile * 0.15);
        }
        addGarageLines(ctx, rows, width, depth, cellCenter, charAt, tile);
      },
    },
  },
  {
    id: "2",
    name: "Level 2",
    classification: 3,
    classificationLabel: "3",
    startFacing: Math.PI * 0.25,
    ceiling: 2.85,
    tile: 2.45,
    fog: { color: 0x59514a, near: 8, far: 34 },
    ambient: 0xb8ab9c,
    ambientIntensity: 0.6,
    hum: { base: 48, buzz: 104, volume: 0.062 },
    createMap: createLevel2Map,
    theme: "level2",
    entities: ["smiler", "deathmoth"],
    reviveMessage: "You wake in the maintenance tunnels.",
    lighting: {
      maxPointLights: 24,
      shouldLight: ({ r, c }) => r % 5 === 2 && c % 5 === 2,
      color: 0xffd7a0,
      intensity: 0.58,
    },
    hooks: level2Hooks,
  },
  {
    id: "3",
    name: "Level 3",
    classification: 4,
    classificationLabel: "4",
    startFacing: Math.PI * 0.5,
    ceiling: 2.75,
    tile: 2.35,
    fog: { color: 0x2c2823, near: 7, far: 31 },
    ambient: 0x6f5948,
    ambientIntensity: 0.34,
    hum: { base: 42, buzz: 94, volume: 0.095 },
    createMap: createLevel3Map,
    theme: "level3",
    entities: ["smiler"],
    reviveMessage: "You wake beneath the metal ceiling.",
    lighting: {
      maxPointLights: 18,
      shouldLight: ({ r, c }) => r % 7 === 3 && c % 8 === 4,
      color: 0xffb16a,
      intensity: 0.42,
    },
    hooks: level3Hooks,
  },
  {
    id: "4",
    name: "Level 4",
    classification: 1,
    classificationLabel: "1",
    startFacing: Math.PI * 0.5,
    ceiling: 3.05,
    tile: 3.0,
    fog: { color: 0x8f948b, near: 18, far: 64 },
    ambient: 0xd7d7c7,
    ambientIntensity: 0.54,
    hum: { base: 54, buzz: 112, volume: 0.045 },
    createMap: createLevel4Map,
    theme: "level4",
    entities: ["hound"],
    reviveMessage: "You wake under the office lights.",
    lighting: {
      maxPointLights: 26,
      shouldLight: ({ r, c }) => r % 5 === 1 && c % 6 === 3,
      color: 0xf4f1dc,
      intensity: 0.66,
    },
    hooks: level4Hooks,
  },
  {
    id: "5",
    name: "Level 5",
    classification: 2,
    classificationLabel: "2",
    startFacing: Math.PI * 0.5,
    ceiling: 3.35,
    tile: 2.9,
    fog: { color: 0x745739, near: 18, far: 68 },
    ambient: 0xf0c582,
    ambientIntensity: 0.62,
    hum: { base: 45, buzz: 88, volume: 0.052 },
    createMap: createLevel5Map,
    theme: "level5",
    entities: ["hound", "deathmoth"],
    deathmothCount: 12,
    reviveMessage: "You wake on the hotel carpet.",
    lighting: {
      maxPointLights: 24,
      shouldLight: ({ r, c }) => r % 4 === 1 && c % 7 === 3,
      color: 0xffba68,
      intensity: 0.76,
    },
    hooks: level5Hooks,
  },
  {
    id: "6",
    name: "Level 6",
    classification: 5,
    classificationLabel: "5",
    startFacing: Math.PI * 0.5,
    ceiling: 2.65,
    tile: 2.35,
    fog: { color: 0x000000, near: 0.5, far: 9 },
    ambient: 0x020202,
    ambientIntensity: 0.012,
    hum: { base: 24, buzz: 36, volume: 0.008 },
    createMap: createLevel6Map,
    theme: "level6",
    reviveMessage: "You wake in the dark.",
    lighting: {
      shouldLight: () => false,
    },
    hooks: level6Hooks,
  },
  {
    id: "7",
    name: "Level 7",
    classification: 4,
    classificationLabel: "4",
    startFacing: Math.PI,
    ceiling: 4.5,
    tile: 3.0,
    fog: { color: 0xa9b8bc, near: 24, far: 115 },
    ambient: 0xd8e2df,
    ambientIntensity: 1.05,
    hum: { base: 28, buzz: 44, volume: 0.018 },
    createMap: createLevel7Map,
    theme: "level7",
    reviveMessage: "You surface beside the entrance room.",
    lighting: {
      shouldLight: () => false,
    },
    hooks: level7Hooks,
  },
];
