import { createLevel0Map } from "./level0.js";
import { createLevel1Map } from "./level1.js";
import { createLevel2Map } from "./level2.js";
import { createLevel3Map } from "./level3.js";
import { createLevel4Map } from "./level4.js";
import { createLevel5Map } from "./level5.js";
import { createLevel6Map } from "./level6.js";

export const LEVELS = [
  {
    id: "0",
    name: "Level 0",
    classification: 1,
    classificationLabel: "1",
    startFacing: Math.PI * 0.5,
    ceiling: 3.15,
    tile: 3.1,
    fog: { color: 0xa99745, near: 18, far: 58 },
    ambient: 0xe1ca77,
    hum: { base: 66, buzz: 118, volume: 0.075 },
    createMap: createLevel0Map,
    theme: "level0",
  },
  {
    id: "1",
    name: "Level 1",
    classification: 2,
    classificationLabel: "2",
    startFacing: Math.PI,
    ceiling: 3.55,
    tile: 3.35,
    fog: { color: 0x9ca19b, near: 11, far: 48 },
    ambient: 0xaeb6a8,
    hum: { base: 57, buzz: 126, volume: 0.055 },
    createMap: createLevel1Map,
    theme: "level1",
    entities: ["hound"],
  },
  {
    id: "2",
    name: "Level 2",
    classification: 3,
    classificationLabel: "3",
    startFacing: Math.PI * 0.25,
    ceiling: 2.85,
    tile: 2.45,
    fog: { color: 0x59514a, near: 8, far: 34 },
    ambient: 0xb8ab9c,
    ambientIntensity: 0.6,
    hum: { base: 48, buzz: 104, volume: 0.062 },
    createMap: createLevel2Map,
    theme: "level2",
    entities: ["smiler", "deathmoth"],
  },
  {
    id: "3",
    name: "Level 3",
    classification: 4,
    classificationLabel: "4",
    startFacing: Math.PI * 0.5,
    ceiling: 2.75,
    tile: 2.35,
    fog: { color: 0x2c2823, near: 7, far: 31 },
    ambient: 0x6f5948,
    ambientIntensity: 0.34,
    hum: { base: 42, buzz: 94, volume: 0.095 },
    createMap: createLevel3Map,
    theme: "level3",
    entities: ["smiler"],
  },
  {
    id: "4",
    name: "Level 4",
    classification: 1,
    classificationLabel: "1",
    startFacing: Math.PI * 0.5,
    ceiling: 3.05,
    tile: 3.0,
    fog: { color: 0x8f948b, near: 18, far: 64 },
    ambient: 0xd7d7c7,
    ambientIntensity: 0.54,
    hum: { base: 54, buzz: 112, volume: 0.045 },
    createMap: createLevel4Map,
    theme: "level4",
    entities: ["hound"],
  },
  {
    id: "5",
    name: "Level 5",
    classification: 2,
    classificationLabel: "2",
    startFacing: Math.PI * 0.5,
    ceiling: 3.35,
    tile: 2.9,
    fog: { color: 0x3b241f, near: 13, far: 48 },
    ambient: 0xd0a066,
    ambientIntensity: 0.44,
    hum: { base: 45, buzz: 88, volume: 0.052 },
    createMap: createLevel5Map,
    theme: "level5",
    entities: ["hound", "deathmoth"],
    deathmothCount: 12,
  },
  {
    id: "6",
    name: "Level 6",
    classification: 5,
    classificationLabel: "5",
    startFacing: Math.PI * 0.5,
    ceiling: 2.65,
    tile: 2.35,
    fog: { color: 0x000000, near: 0.5, far: 9 },
    ambient: 0x020202,
    ambientIntensity: 0.012,
    hum: { base: 24, buzz: 36, volume: 0.008 },
    createMap: createLevel6Map,
    theme: "level6",
  },
];
